# Generated by Django 4.1.5 on 2023-08-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persion',
            old_name='Num',
            new_name='age',
        ),
    ]
